# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5eaf6b381099a8726e589c15f9ffc159aeed38a1dd8e44022d47210bc44939836ee5e94c3985b442f44caee9f1d16a3428839e34238439e3fe8ecc3ebdf097df

test:
  secret_key_base: e41f39c622e8feeadfd931a1e0eb9ada529e229ba187a623511887ddfcf62c5412872b70230ff8797536261de2f2fd46a6b766c8fcecd4027f40a56e87a538c6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
